name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
     - dev

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: us-west-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: "Built and push image"
              env:
                 ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  
                 ECR_REPOSITORY: "myhome-dev"
                 #IMAGE_TAG: ${{ github.run_number }}
                 IMAGE_TAG: "latest"
              run: |
                docker build -t build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    Deploy:
         needs: Build
         runs-on: ubuntu-latest
         steps:
            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.REMOTE_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                envs: |
                  ECR_REGISTRY=$ECR_REGISTRY
                  ECR_REPOSITORY=$ECR_REPOSITORY
                  IMAGE_TAG=$IMAGE_TAG
                  ls -la
                  docker prune -af
                  docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
               
              
