name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
     - dev
env:
    IMAGE_NAME: "myhome-dev"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4

            - name: "Built image"
              run: |
                docker build -t ${{ env.IMAGE_NAME }}:latest -f ./MyHomeNet/Dockerfile .