name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
     - dev
env:
    IMAGE_NAME: "myhome-dev"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: eu-central-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v4

            - name: "Built image"
              env:
                 ECR_REGISTRY: 198783273856.dkr.ecr.eu-central-1.amazonaws.com
                 ECR_REPOSITORY: myhome
              
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f ./MyHomeNet/Dockerfile .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY